travis:
  secure:
    BINSTAR_TOKEN: fth1D8qjm2doeJEzUXosW7IRZXoYbfK5ncTqiDNfQJm8zS69P5rzp4pnJOipCsTJK5PpfcEK4JZs7UXDDrMlKRosJos0Q71e5qdwOmwS6TcIGsj1gUtXyBkPBhz6aMJVFv+BBsl4hemQB/+6XwrchmaF0Lqt0VX861SRCU/L8tTJXgiFCYraiqapNG67P5OQuvekKBcglS3sxsI22N0xNhs84V8ZTi42EI4BorItdW505Rh+vqA7R/2HoM0ARBut1jcey32BMZWHEIdlA5XTyUOdOFBXxA67TQjlCjdn47EPfLbipjTMPpzzIwU85zwrMXvC+uzTZyb4fJTimy+iRc5v4jHrKOx3a086Jknqu6LOyuLGDPwBHrMLZhPh2MSlDcm79ndrBVW2U7cLEbEJf45NHDFrlhDYkgnJA+CI2sf4O3f3HvKOSGUEqJO1AMhOHXTt4cbdQ9M5xRE+ctj4TND7Y8wC+nJk80L1vBHcSVEzw4vWAMCrfJP2dFhKN4b6gxY+r1Vl7AgTRSHr4FIWCiWpuLJenQRwDZpjP+vn8r1NKAdOFjrWKRNCB4RN35nL2PDOobm3CGhEr9SAakvUe0E3WNjSdEMVLYuxAZQzUWG2t5oulbsEorMGZ0WWiuNZ7Tu9XLCtwefHKy7b8og5hi9enpsM7sowdh1lhhtSzDM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
